//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int activityId { get; set; }
        public string activityName { get; set; }
        public int hours { get; set; }
        public System.DateTime activityDate { get; set; }
        public int userConsumer { get; set; }
        public int userProducer { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
